# FocusLens — cv/config package
from .settings import (
    CAMERA_INDEX,
    CAMERA_WIDTH,
    CAMERA_HEIGHT,
    TARGET_FPS,
    FRAME_SCALE,
    INTERNAL_COLOR_SPACE,
    # MediaPipe Face Landmarker (Day 05+)
    MEDIAPIPE_MODEL_PATH,
    FACE_DETECTION_CONFIDENCE,
    FACE_PRESENCE_CONFIDENCE,
    MAX_FACES,
    # Dev / debug
    SHOW_DEV_PREVIEW,
    DEV_PREVIEW_WINDOW_TITLE,
    SHOW_OVERLAY_INFO,
    SHOW_LANDMARK_OVERLAY,
    OVERLAY_TEXT_COLOR,
    OVERLAY_TEXT_SCALE,
    OVERLAY_TEXT_THICKNESS,
    LOG_LEVEL,
)

__all__ = [
    "CAMERA_INDEX",
    "CAMERA_WIDTH",
    "CAMERA_HEIGHT",
    "TARGET_FPS",
    "FRAME_SCALE",
    "INTERNAL_COLOR_SPACE",
    "MEDIAPIPE_MODEL_PATH",
    "FACE_DETECTION_CONFIDENCE",
    "FACE_PRESENCE_CONFIDENCE",
    "MAX_FACES",
    "SHOW_DEV_PREVIEW",
    "DEV_PREVIEW_WINDOW_TITLE",
    "SHOW_OVERLAY_INFO",
    "SHOW_LANDMARK_OVERLAY",
    "OVERLAY_TEXT_COLOR",
    "OVERLAY_TEXT_SCALE",
    "OVERLAY_TEXT_THICKNESS",
    "LOG_LEVEL",
]
