# FocusLens — cv/config package
from .settings import (
    CAMERA_INDEX,
    CAMERA_WIDTH,
    CAMERA_HEIGHT,
    TARGET_FPS,
    FRAME_SCALE,
    INTERNAL_COLOR_SPACE,
    SHOW_DEV_PREVIEW,
    DEV_PREVIEW_WINDOW_TITLE,
    SHOW_OVERLAY_INFO,
    OVERLAY_TEXT_COLOR,
    OVERLAY_TEXT_SCALE,
    OVERLAY_TEXT_THICKNESS,
    LOG_LEVEL,
)

__all__ = [
    "CAMERA_INDEX",
    "CAMERA_WIDTH",
    "CAMERA_HEIGHT",
    "TARGET_FPS",
    "FRAME_SCALE",
    "INTERNAL_COLOR_SPACE",
    "SHOW_DEV_PREVIEW",
    "DEV_PREVIEW_WINDOW_TITLE",
    "SHOW_OVERLAY_INFO",
    "OVERLAY_TEXT_COLOR",
    "OVERLAY_TEXT_SCALE",
    "OVERLAY_TEXT_THICKNESS",
    "LOG_LEVEL",
]
