"""Confidence and debounce thresholds for CV state tracking."""

PRESENCE_CONSECUTIVE_DETECTION_THRESHOLD: int = 3
PRESENCE_CONSECUTIVE_MISSING_THRESHOLD: int = 5

SCREEN_FACING_MIN_CONFIDENCE: float = 0.15
SCREEN_FACING_CONSECUTIVE_STATE_THRESHOLD: int = 3
SCREEN_FACING_CONSECUTIVE_UNKNOWN_THRESHOLD: int = 3
